# Generated by Django 3.0.3 on 2020-09-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='music_download',
            field=models.URLField(default='http://localhost:3000/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='music_stream',
            field=models.URLField(default='http://localhost:3000/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='music_content',
            field=models.TextField(),
        ),
    ]
