# Generated by Django 3.0.3 on 2020-09-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
            preserve_default=False,
        ),
    ]
