# Generated by Django 3.0.3 on 2020-09-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200916_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
    ]
