# Generated by Django 3.0.3 on 2020-09-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-timestamp']},
        ),
    ]
