# Generated by Django 3.0.3 on 2020-09-15 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200913_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_action',
            field=models.ManyToManyField(blank=True, related_name='blog_action', through='blog.Action', to=settings.AUTH_USER_MODEL),
        ),
    ]
